const x = async do { throw new Error("sync") };
